Anton
romul3003/evita pull request #6
Opened 2018-02-22 19:43 UTC by nedoponimayu

2018-02-22 19:59 UTC, roman-vabishchevych requested changes

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/assets/styles/main.styl
> +.main-tilte
відкотити цей хук

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/blocks/mainfirstblock/mainfirstblock.pug
> +					div
тут не повинно бути неназваних div

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/blocks/mainfirstblock/mainfirstblock.pug
> +					div
назвати елемент

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/blocks/mainfirstblock/mainfirstblock.pug
> +				+e.col-sm-7.underpic
переіменувати елемент col-sm-7

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/blocks/mainfirstblock/mainfirstblock.styl
> +	&__col-sm-7.underpic
переіменувати елемент col-sm-7 в underpic

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/index.pug
> +	block mainfirstblock
видалити block mainfirstblock

2018-02-22 19:59 UTC, roman-vabishchevych commented on src/layouts/main.pug
> +	link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="an
випилити бутстрап

2018-02-25 15:01 UTC, nedoponimayu commented
Внес изменения

2018-02-26 05:49 UTC, roman-vabishchevych commented
ще не по всім коментарям виправлено

2018-02-26 17:31 UTC, nedoponimayu commented
Вот сейчас должно быть все.

2018-03-05 09:51 UTC, roman-vabishchevych commented on src/blocks/mainfirstblock/mainfirstblock.pug
> +mixin mainfirstblock()
міксін має називатись з префіксом b-
`b-mainfirstblock`

2018-03-05 09:51 UTC, roman-vabishchevych commented on src/index.pug
> +block content
тут мабуть треба викликати твій блок? +b-mainfirstblock()

2018-03-05 09:51 UTC, roman-vabishchevych commented
по змінам все ок.
є два незначні коменти.
виправи їх, конфлікти і роби merge

2018-03-05 17:28 UTC, merged